CONTIKI_PROJECT = hello-world
all: $(CONTIKI_PROJECT)

CONTIKI = ../../..

# Include the ESP32-S3 platform
PLATFORMS_ONLY = esp32-s3

# Optional: Node ID
MAKE_MAC = MAKE_MAC_FROM_ID
MAKE_NET = MAKE_NET_FROM_ID

include $(CONTIKI)/Makefile.include
