idf_component_register(
    SRCS 
        "../hello-world.c"
        "${CONTIKI}/os/sys/autostart.c"
    INCLUDE_DIRS 
        ".."
        "${CONTIKI}/os"
        "${CONTIKI}/os/sys"
        "${CONTIKI}/os/dev"
        "${CONTIKI}/arch/platform/esp32-s3"
        "${CONTIKI}/arch/cpu/esp32-s3"
    REQUIRES 
        esp32-s3
)
