/*
 * Minimal sdkconfig.h for Contiki-NG ESP32-S3 port
 * This file provides minimal ESP-IDF configuration needed for compilation
 */

#ifndef SDKCONFIG_H
#define SDKCONFIG_H

/* ESP32-S3 chip */
#define CONFIG_IDF_TARGET_ESP32S3 1
#define CONFIG_IDF_TARGET "esp32s3"
#define CONFIG_IDF_FIRMWARE_CHIP_ID 0x0009

/* CPU Configuration */
#define CONFIG_ESP32S3_DEFAULT_CPU_FREQ_MHZ 240
#define CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ 240

/* Console UART */
#define CONFIG_ESP_CONSOLE_UART 1
#define CONFIG_ESP_CONSOLE_UART_NUM 0
#define CONFIG_ESP_CONSOLE_UART_BAUDRATE 115200

/* Memory */
#define CONFIG_ESP32S3_INSTRUCTION_CACHE_SIZE 0x4000
#define CONFIG_ESP32S3_DATA_CACHE_SIZE 0x10000
#define CONFIG_ESP32S3_SPIRAM_SUPPORT 0

/* Bootloader */
#define CONFIG_BOOTLOADER_OFFSET_IN_FLASH 0x0

/* Flash */
#define CONFIG_ESPTOOLPY_FLASHMODE_QIO 1
#define CONFIG_ESPTOOLPY_FLASHFREQ_80M 1
#define CONFIG_ESPTOOLPY_FLASHSIZE_4MB 1
#define CONFIG_ESPTOOLPY_FLASHSIZE "4MB"

/* NVS */
#define CONFIG_NVS_ENCRYPTION 0

/* Log output */
#define CONFIG_LOG_DEFAULT_LEVEL 3
#define CONFIG_LOG_DEFAULT_LEVEL_INFO 1
#define CONFIG_LOG_MAXIMUM_LEVEL 5

/* Watchdog */
#define CONFIG_ESP_TASK_WDT 1
#define CONFIG_ESP_TASK_WDT_TIMEOUT_S 5

/* FreeRTOS - disabled for Contiki-NG */
#define CONFIG_FREERTOS_HZ 100
#define CONFIG_FREERTOS_UNICORE 0

/* Newlib - Essential for stdio */
#define CONFIG_NEWLIB_STDOUT_LINE_ENDING_CRLF 1
#define CONFIG_NEWLIB_STDIN_LINE_ENDING_CR 1
#define CONFIG_NEWLIB_NANO_FORMAT 0

/* System */
#define CONFIG_ESP_SYSTEM_EVENT_QUEUE_SIZE 32
#define CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE 2304

/* Minimal feature set for bare-metal Contiki-NG */
#define CONFIG_ESP_SYSTEM_SINGLE_CORE_MODE 0
#define CONFIG_ESP_INT_WDT 1
#define CONFIG_ESP_INT_WDT_TIMEOUT_MS 300

/* Timer */
#define CONFIG_GPTIMER_ISR_IRAM_SAFE 1
#define CONFIG_GPTIMER_CTRL_FUNC_IN_IRAM 1

/* Cache */
#define CONFIG_ESP32S3_INSTRUCTION_CACHE_16KB 1
#define CONFIG_ESP32S3_DATA_CACHE_64KB 1

#endif /* SDKCONFIG_H */
